/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tsys.tc_spike;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
//		final SpringApplication application = new SpringApplication(PaymentsApplication.class)
//		application.setDefaultProperties(Collections.singletonMap("server.port", "9000"));
//		application.run(args);
    }
}
